apiVersion: v1
kind: Namespace
metadata:
  name: sonarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sonarr
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: ghcr.io/home-operations/sonarr:rolling
          ports:
            - containerPort: 8989
          volumeMounts:
            - mountPath: /mnt/Medienbibliothek
              name: medienbibliothek
      volumes:
        - name: medienbibliothek
          nfs:
            server: 192.168.0.56
            path: /volume1/Medienbibliothek
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: sonarr
spec:
  selector:
    app: sonarr
  ports:
    - port: 8989
      targetPort: 8989