apiVersion: v1
kind: Namespace
metadata:
  name: radarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: radarr
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: ghcr.io/home-operations/radarr:rolling
          ports:
            - containerPort: 8989
          volumeMounts:
            - mountPath: /mnt/Medienbibliothek
              name: medienbibliothek
      volumes:
        - name: medienbibliothek
          nfs:
            server: 192.168.0.56
            path: /volume1/Medienbibliothek
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: radarr
spec:
  selector:
    app: radarr
  ports:
    - port: 8989
      targetPort: 8989