apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jellyfin
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: ghcr.io/jellyfin/jellyfin:latest
          ports:
            - containerPort: 8096
          volumeMounts:
            - mountPath: /mnt/Medienbibliothek
              name: medienbibliothek
            - mountPath: /dev/dri
              name: quicksync
      volumes:
        - name: medienbibliothek
          nfs:
            server: 192.168.0.56
            path: /volume1/Medienbibliothek/Medien
            readOnly: true
        - name: quicksync
          hostPath:
            path: /dev/dri
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
  - port: 8096
    targetPort: 8096