apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jellyfin
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
          runAsUser: 0
          runAsGroup: 0
          supplementalGroups:
            - 105
      containers:
        - name: jellyfin
          image: ghcr.io/jellyfin/jellyfin:latest
          ports:
            - containerPort: 8096
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              gpu.intel.com/i915: 1000m

          volumeMounts:
            - mountPath: /mnt/Medienbibliothek
              name: medienbibliothek
            - mountPath: /config
              name: jellyfin-config
            - mountPath: /transcode
              name: jellyfin-transcode
      volumes:
        - name: medienbibliothek
          nfs:
            server: 192.168.0.56
            path: /volume1/Medienbibliothek/Medien
            readOnly: true
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-pvc
        - name: jellyfin-transcode
          emptyDir: 
            medium: Memory
            sizeLimit: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
  - port: 8096
    targetPort: 8096
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---