apiVersion: v1
kind: Namespace
metadata:
  name: prowlarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prowlarr
  name: prowlarr
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/home-operations/prowlarr:rolling
          ports:
            - containerPort: 9696
          volumeMounts:
            - mountPath: /mnt/Medienbibliothek
              name: medienbibliothek
      volumes:
        - name: medienbibliothek
          nfs:
            server: 192.168.0.56
            path: /volume1/Medienbibliothek
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  selector:
    app: prowlarr
  ports:
    - port: 9696
      targetPort: 9696